package br.senai.sc.trunfo.model.enums;

public enum ImageType {
    // Alive
    STOAT, STINKBUG, STUNTEDWOLF,
    // Canine
    WOLFCUB, WOLF, COYOTE, BLOODHOUND, ALPHA,
    // Special
    URAYULI, GRIZZLY, GREATWHITE, AMOEBA, AMALGAM, MOLEMAN,
    // Avian
    TURKEYVULTURE, SPARROW, RAVENEGG, RAVEN, MAGPIE, KINGFISHER,
    // Rodent
    RATKING, FIELDMICE, BEAVER, SQUIRREL, RABBIT, PORCUPINE,
    // Insect
    STRANGELARVA, STRANGEPUPA, MOTHMAN, BEE, RINGWORM, ANTQUEEN,
    MANTISGOD, MANTIS, WORKERANT, CORPSEMAGGOTS, COCKROACH, BEEHIVE,
    // Reptile
    GECK, SKINK, RATTLER, ADDER, BULLFROG, RIVERSNAPPER, OUROBOROS,
    // Hooved
    CHILD13, LONGELK, BLACKGOAT, ELKFAWN, ELK, PRONGHORN, MOOSEBUCK,
    // Smoke
    THESMOKE ,GREATERSMOKE,
    // Misc
    OPOSSUM, RIVEROTTER, BAT, SKUNK, CAT, UNDEADCAT, MOLE
}
